name: Veracode SAST Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests
        working-directory: app  # Ajuste se o pom.xml estiver na raiz ou numa subpasta específica

      - name: Veracode Upload And Scan
        uses: veracode/veracode-uploadandscan-action@master
        with:
          appname: 'Jonatas Emerick Technical Panel'
          createprofile: true
          filepath: 'app/target/verademo.war' # Ajuste o caminho para onde o .war foi gerado
          vid: ${{ secrets.VERACODE_API_ID }}
          vkey: ${{ secrets.VERACODE_API_KEY }}
          sandboxname: 'Github'
          createsandbox: false